name: Release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: true

env:
  VERSION: ${{ inputs.releaseTag }}

jobs:
  #BuildAndPushDockerImages:
  #  strategy:
  #    matrix:
  #      image:
  #        - amd64
  #        - arm32v7
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: docker/setup-qemu-action@v2
  #    - uses: docker/setup-buildx-action@v2
  #      id: buildx
  #      with:
  #        install: true
  #    - name: Login to docker hub
  #      run: |
  #        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
  #    - name: Build and push images
  #      run: |
  #        docker buildx build -f "./LoRaEngine/modules/LoRaWanNetworkSrvModule/Dockerfile.${{ matrix.image }}" -t $DOCKERHUB_ORGANISATION/lorawannetworksrvmodule:$VERSION-${{ matrix.image }} --output type=image,push=true "."
  #        docker buildx build -f "./LoRaEngine/modules/LoRaBasicsStationModule/Dockerfile.${{ matrix.image }}" -t $DOCKERHUB_ORGANISATION/lorabasicsstationmodule:$VERSION-${{ matrix.image }} --build-arg SOURCE_CONTAINER_REGISTRY_ADDRESS=docker.io --output type=image,push=true "."
  #    - name: Create manifests
  #      run: |
  #        docker manifest create $DOCKERHUB_ORGANISATION/lorawannetworksrvmodule:$VERSION $DOCKERHUB_ORGANISATION/lorawannetworksrvmodule:$VERSION-${{ matrix.image }} --amend
  #        docker manifest create $DOCKERHUB_ORGANISATION/lorabasicsstationmodule:$VERSION $DOCKERHUB_ORGANISATION/lorabasicsstationmodule:$VERSION-${{ matrix.image }} --amend
  #        docker manifest push $DOCKERHUB_ORGANISATION/lorabasicsstationmodule:$VERSION
  #        docker manifest push $DOCKERHUB_ORGANISATION/lorawannetworksrvmodule:$VERSION
  #  env: 
  #    DOCKERHUB_ORGANISATION: "ouphi"

  CreateRelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Azure Function
        run: |
          dotnet publish LoRaEngine/LoraKeysManagerFacade -c Release
          FUNCTION_ZIP=function-${VERSION}.zip
          zip -r $FUNCTION_ZIP LoRaEngine/LoraKeysManagerFacade/bin/Release/net6.0
          # Define FUNCTION_ZIP env var for next steps.
          echo "FUNCTION_ZIP=$FUNCTION_ZIP" >> $GITHUB_ENV
      - name: Package Discovery Service
        run: |
          dotnet publish LoRaEngine/modules/LoRaWan.NetworkServerDiscovery/LoRaWan.NetworkServerDiscovery.csproj -c Release
          PUBLISH_FOLDER=LoRaEngine/modules/LoRaWan.NetworkServerDiscovery/bin/Release/net6.0/publish
          DISCOVERY_SERVICE_ZIP=discoveryservice-${VERSION}.beta1.zip
          zip -r $DISCOVERY_SERVICE_ZIP $PUBLISH_FOLDER
          # Define DISCOVERY_SERVICE_ZIP env var for next steps.
          echo "DISCOVERY_SERVICE_ZIP=$DISCOVERY_SERVICE_ZIP" >> $GITHUB_ENV
      - name: Generate ARM file
        working-directory: TemplateBicep
        run: |
          az bicep build --file main.bicep
          az bicep build --file main.bicep --outfile $ARM_FILE
      - name: Compile provisioning CLI
        working-directory: Tools/Cli-LoRa-Device-Provisioning
        run: |
          for PLATFORM in win10-x64 linux-x64 osx-x64
          do
            dotnet publish -c Release -r $PLATFORM
            ZIP_NAME=device-provisioning-cli-$PLATFORM.zip
            zip -r ZIP_NAME bin/Release/net6.0/osx-x64/publish/
            ZIP_VAR_NAME=$(echo "PROVISIONING_CLI_$PLATFORM" | tr '-' '_')
            echo "$ZIP_VAR_NAME=Tools/Cli-LoRa-Device-Provisioning/$ZIP_NAME" >> $GITHUB_ENV
          done
      - name: Release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create v$VERSION TemplateBicep/$ARM_FILE $FUNCTION_ZIP $DISCOVERY_SERVICE_ZIP \
             $PROVISIONING_CLI_win10_x64 $PROVISIONING_CLI_linux_x64 $PROVISIONING_CLI_osx_x64 \
            --title "Release v$VERSION" --prerelease --repo ${{ github.repository }} --notes ""
    #needs: BuildAndPushDockerImages
    env:
      ARM_FILE: azuredeploy.json
