name: Release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: true
jobs:
  BuildAndPushDockerImages:
    env:
      ORGANISATION: "ouphi"
      VERSION: ${{ inputs.releaseTag }}
    strategy:
      matrix:
        image:
          - amd64
          - arm32v7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push images
        run: |
          docker buildx build -f "./LoRaEngine/modules/LoRaWanNetworkSrvModule/Dockerfile.${{ matrix.image }}" -t $ORGANISATION/lorawannetworksrvmodule:$VERSION-${{ matrix.image }} --output type=image,push=true "."
          docker buildx build -f "./LoRaEngine/modules/LoRaBasicsStationModule/Dockerfile.${{ matrix.image }}" -t $ORGANISATION/lorabasicsstationmodule:$VERSION-${{ matrix.image }} --build-arg SOURCE_CONTAINER_REGISTRY_ADDRESS=docker.io --output type=image,push=true "."
      - name: Create manifests
        run: |
          docker manifest create $ORGANISATION/lorawannetworksrvmodule:$VERSION $ORGANISATION/lorawannetworksrvmodule:$VERSION-${{ matrix.image }} --amend
          docker manifest create $ORGANISATION/lorabasicsstationmodule:$VERSION $ORGANISATION/lorabasicsstationmodule:$VERSION-${{ matrix.image }} --amend
          docker manifest push $ORGANISATION/lorabasicsstationmodule:$VERSION
          docker manifest push $ORGANISATION/lorawannetworksrvmodule:$VERSION